# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'aws-sdk-ecs'
gem 'aws-sdk-applicationautoscaling'
gem 'jimuguri'
gem 'terminal-table'
gem 'highline'
